version: "3.9"  # optional since v1.27.0
services:
  backend:
    image: translation-backend:v0.2.0 # working: v0.1.0
    volumes:
      - ./backend/cache:/app/cache
    network_mode: "host"
  frontend:
    image: translation-frontend:v0.1.0
    network_mode: "host"
