apiVersion: v1
kind: List
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: KN-translator
      build: translator-backend
      template: translator-backend-build
    name: translator-backend
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: translator-backend:latest
    runPolicy: Serial
    source:
      type: Binary
    strategy:
      dockerStrategy:
        forcePull: true
        noCache: true
      type: Docker
    successfulBuildsHistoryLimit: 5
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: KN-translator
      build: translator-backend
      template: translator-backend-build
    name: translator-backend
  spec:
    lookupPolicy:
      local: false
